version: "3.6"
services:
    pdf-microsservice:
        build:
            context: ./
            dockerfile: ./Dockerfile
        image: pdf-microsservice
        command: ./startup.sh
        ports:
            - "9191:80"
